// Random facts for each character
function getFacts(person) {
  const facts = {
    'hamid': [
  'Hamid once traveled across the Sahara Desert with nothing but a compass and a backpack.',
  'He can speak 7 different languages fluently.',
  'Hamid is a self-taught coder and a chess grandmaster.',
  'He once built a fully functioning computer out of scrap parts he found in a junkyard.',
  'Hamid is known for his unique ability to solve complex problems in record time.',
  'He once climbed Mount Kilimanjaro in just 3 days.',
  'Hamid loves extreme sports and has skydived from 15,000 feet.',
  'He’s an avid reader and has read over 1,000 books on various subjects.',
  'Hamid can play multiple musical instruments, including the piano and guitar.',
  'He once built a robot that could play chess and beat professional players.',
  'Hamid has traveled to over 50 countries, learning from different cultures.',
  'He’s known for his photographic memory, able to recall any fact he’s read or heard.',
  'Hamid once solved a Rubik’s cube blindfolded in under 2 minutes.',
  'He is a strong advocate for education and has set up several schools in underprivileged areas.',
  'Hamid is a master of puzzles, often creating his own challenging games for others to solve.',
  'He once hacked into his own computer security system to prove a point.',
  'Hamid has written several papers on artificial intelligence that are studied at top universities.',
  'He can identify any country on a map in under 10 seconds.',
  'Hamid once built a solar-powered car and drove it across a desert.',
  'He is known for his ability to pick up new skills incredibly quickly.',
  'Hamid once meditated for a week straight in the mountains to clear his mind before a big project.',
  'He has won multiple coding competitions, beating some of the best in the world.',
  'Hamid’s chess skills are so advanced that he can play and win multiple games at once.',
  'He can cook dishes from every country he’s visited, mastering various cuisines.',
  'Hamid is a certified deep-sea diver and has explored shipwrecks in different oceans.',
  'He once gave a TED Talk on the future of technology and its impact on education.',
  'Hamid has developed several open-source projects used by thousands of developers.',
  'He once repaired a broken satellite communication system while camping in a remote area.',
  'Hamid is a black belt in karate and has trained in martial arts for over 10 years.',
  'He can run a marathon without breaking a sweat and has completed several.',
  'Hamid has created his own encryption algorithm that’s nearly impossible to crack.',
  'He once wrote an entire novel in just two weeks during a creative writing challenge.',
  'Hamid has developed an app that teaches children how to code in a fun and interactive way.',
  'He is known for his philanthropic work, especially in the field of education technology.',
  'Hamid once saved a village from a natural disaster by predicting it days in advance.',
  'He can recite Pi to over 500 decimal places from memory.',
  'Hamid is a master of origami and can fold a paper crane in under 10 seconds.',
  'He has built his own personal library filled with rare and ancient books.',
  'Hamid once designed a system to purify water for a remote village, giving them access to clean drinking water.',
  'He can write code in over 10 programming languages with ease.',
  'Hamid is also an excellent photographer, capturing moments from his travels.',
  'He once spent a year living off the grid, relying on his survival skills and technology he built himself.',
  'Hamid is known for his calm under pressure, often solving problems that stump others.',
  'He once participated in a worldwide treasure hunt and found the final clue hidden in an ancient ruin.',
  'Hamid is a coffee connoisseur and has brewed coffee using beans from around the world.',
  'He has developed a drone that can deliver supplies to remote areas.',
  'Hamid can play chess without a board, visualizing all the moves in his head.',
  'He once wrote an AI algorithm that helps predict stock market trends with great accuracy.',
  'Hamid has competed in international math competitions and won several gold medals.',
  'He has developed a language-learning app that adapts to the user’s learning style.',
  'Hamid has climbed the tallest mountains on five different continents.',
  'He’s a minimalist and believes in living with only the essentials.',
  'Hamid can calculate complex equations in his head faster than most people can with a calculator.',
  'He once built a working 3D printer from scratch.',
  'Hamid has spent years studying ancient civilizations and their contributions to modern technology.',
  'He’s known for his incredible sense of direction, never getting lost even in unfamiliar places.',
  'Hamid has developed an AI that can write music based on a few inputs from the user.',
  'He once won a trivia contest against a supercomputer.',
  'Hamid enjoys stargazing and can identify nearly every constellation.',
  'He has participated in humanitarian missions, using his engineering skills to improve infrastructure.',
  'Hamid can code faster than most people can type regular text.',
  'He once taught an entire class on quantum physics in just one hour.',
  'Hamid has competed in multiple triathlons and placed in the top 10 each time.',
  'He’s a master of time management, able to balance multiple projects simultaneously.',
  'Hamid once broke a world record for the most coding problems solved in 24 hours.',
  'He’s known to be able to solve Sudoku puzzles of the highest difficulty in minutes.',
  'Hamid has helped design space exploration technology used by international space agencies.',
  'He can navigate the most complex subway systems without a map.',
  'Hamid is an expert in virtual reality and has developed several VR-based training programs.',
  'He once programmed a robot to write poetry based on the emotions of people around it.',
  'Hamid can build fully functional computers from scratch in under a day.',
  'He has invented a device that can translate languages in real-time.',
  'Hamid has developed a personal AI assistant that helps him organize his day efficiently.',
  'He once hiked through a jungle to find a rare plant species for research purposes.',
  'Hamid is an advocate for renewable energy and has designed solar-powered houses.',
  'He has studied under some of the greatest minds in the fields of science and technology.',
  'Hamid once saved a major tech conference by fixing the main presentation system minutes before it started.',
  'He’s skilled at coding games, having developed several that are now used for educational purposes.',
  'Hamid has built robots that can mimic human movement with astonishing precision.',
  'He has been awarded numerous patents for his innovative tech designs.',
  'Hamid once repaired an airplane’s navigation system mid-flight, preventing disaster.',
  'He’s a master debater and has won multiple international debate competitions.',
  'Hamid once discovered a hidden cave system while exploring the wilderness.',
  'He’s developed an app that helps farmers optimize their crop production.',
  'Hamid can recite entire books from memory, including some of the longest novels ever written.',
  'He has created a revolutionary new operating system that’s being adopted by major companies.',
  'Hamid once reverse-engineered a highly complex machine to understand its inner workings.',
  'He’s been invited to speak at universities around the world about his innovative work.',
  'Hamid has developed a health app that monitors vital signs and predicts potential illnesses.',
  'He once broke a secret code that had baffled experts for years.',
  'Hamid has swum with sharks while researching marine life.',
  'He once led a team of scientists to discover a new species of insect in the Amazon.',
  'Hamid has mastered the art of speed reading, able to read an entire book in an afternoon.',
  'He can draw detailed maps from memory after only seeing a place once.',
  'Hamid once created a drone that can navigate autonomously through dense forests.',
  'He’s known for his ability to take on projects that seem impossible and succeed.',
  'Hamid once designed an entire city plan that was implemented in a rapidly growing metropolis.',
  'He is often sought after for his advice on cutting-edge technology and innovation.'
],

    'anders': [
  'Anders the Rizz II is known for his legendary charisma and charm.',
  'He once convinced an entire crowd to do the wave, just by raising his hand.',
  'Anders can talk his way out of any situation, no matter how tricky.',
  'He has a natural ability to win people over in under 30 seconds.',
  'Anders once talked his way into a private concert by a world-famous artist.',
  'He is so charming that even animals are drawn to him.',
  'Anders can convince a room full of people to agree with him without saying a word.',
  'He’s fluent in the art of persuasion and has never lost an argument.',
  'Anders once convinced a rival kingdom to surrender without lifting a sword.',
  'His nickname, "The Rizz," comes from his unmatched ability to "rizz" anyone up.',
  'Anders once started a spontaneous flash mob in the middle of a busy marketplace.',
  'He once talked his way into a high-security vault just to prove he could.',
  'Anders has a talent for convincing anyone to share their deepest secrets with him.',
  'He once managed to get free food for a whole week just by chatting with a restaurant owner.',
  'Anders has a gift for public speaking and can mesmerize an audience for hours.',
  'He can make even the most serious person laugh within minutes of meeting them.',
  'Anders once convinced a dragon to leave a village alone, just by complimenting it.',
  'He’s known for his smooth, charismatic voice that makes people stop and listen.',
  'Anders once won a debate without even knowing the topic beforehand.',
  'He has an uncanny ability to remember people’s names, even if he’s only met them once.',
  'Anders can talk his way out of speeding tickets every single time.',
  'He once convinced an entire tavern to sing along with him during a performance.',
  'Anders can defuse any tense situation with just a few words.',
  'He’s been known to talk his way into exclusive events and parties without an invitation.',
  'Anders once persuaded a group of pirates to give up their treasure peacefully.',
  'He has a way of making everyone feel like the most important person in the room.',
  'Anders once talked his way into getting a royal feast prepared just for him.',
  'He’s known for his silver tongue, always knowing the right thing to say at the right time.',
  'Anders has convinced entire kingdoms to change their policies based on a single conversation.',
  'He once negotiated peace between two warring tribes with nothing but his words.',
  'Anders can talk someone into giving him their last gold coin and thank him for it afterward.',
  'He once helped a friend win a debate championship without ever reading the topic.',
  'Anders has been known to convince people to dance, even when no music is playing.',
  'He once charmed his way into a royal ball dressed as a simple commoner.',
  'Anders can sell ice to an Eskimo and sand to someone in the desert.',
  'He once talked his way into getting an entire city to follow him on a parade through town.',
  'Anders is a natural-born leader, with people often following him without question.',
  'He once convinced a group of knights to surrender their weapons without a fight.',
  'Anders has the ability to make everyone around him feel at ease, no matter the situation.',
  'He once talked his way into getting the finest room in the kingdom’s grandest hotel for free.',
  'Anders can diffuse arguments with just a wink and a smile.',
  'He’s known for his ability to get anyone to do a favor for him, no matter how difficult.',
  'Anders once talked his way into becoming a guest of honor at a royal banquet.',
  'He convinced a ship’s captain to take him on an adventure across the sea, free of charge.',
  'Anders has never been turned down for a dance, no matter who the partner is.',
  'He once convinced a wild animal to let him pass unharmed, just by speaking softly to it.',
  'Anders has persuaded shopkeepers to give him discounts on goods without even trying.',
  'He once talked an enemy spy into switching sides during an intense negotiation.',
  'Anders once convinced a guard to let him into a fortress without showing any papers.',
  'He’s known for his smooth negotiation tactics that always end in his favor.',
  'Anders once talked a famous chef into cooking him a special meal that wasn’t on the menu.',
  'He can charm anyone he meets, from peasants to royalty.',
  'Anders once talked a prince out of a duel, saving the kingdom from disaster.',
  'He once convinced a wizard to reveal the secrets of an ancient spellbook.',
  'Anders has a talent for getting people to trust him instantly, no matter the circumstances.',
  'He once convinced a merchant to give him a priceless artifact in exchange for a simple favor.',
  'Anders once turned a tense political meeting into a celebration with his witty charm.',
  'He once persuaded an entire village to throw a festival in his honor.',
  'Anders once got a crowd to cheer for him during a performance he wasn’t even part of.',
  'He can win over even the toughest of critics with his charismatic personality.',
  'Anders once talked his way out of being arrested by charming the guards.',
  'He’s known for his quick wit and ability to turn any situation into a positive one.',
  'Anders once convinced a group of mercenaries to switch sides in a war.',
  'He once talked a dragon into giving him a ride across the mountains.',
  'Anders has the ability to talk someone into giving him their seat at a crowded event.',
  'He once persuaded a king to change a law during a casual conversation over tea.',
  'Anders can win a debate even if he’s arguing the side he doesn’t believe in.',
  'He once convinced a famous artist to paint his portrait, free of charge.',
  'Anders has talked his way out of more battles than anyone can count.',
  'He’s known for his ability to make people laugh, even in the most serious situations.',
  'Anders once convinced a group of bandits to turn themselves in peacefully.',
  'He can charm someone into letting him borrow their horse for a long journey.',
  'Anders once convinced a group of musicians to play his favorite song for hours.',
  'He’s been known to talk people into giving him valuable items without them realizing it.',
  'Anders once talked his way into a royal wedding as a special guest.',
  'He’s so charming that even his rivals find it hard to dislike him.',
  'Anders once convinced an entire city to throw him a farewell party.',
  'He’s known for his ability to diffuse tension in diplomatic meetings with ease.',
  'Anders once talked his way into getting a private tour of a royal palace.',
  'He once convinced a rival leader to agree to a truce just by having a conversation over dinner.',
  'Anders can get anyone to follow him into an adventure, no matter how dangerous.',
  'He’s known for his ability to talk his way into exclusive clubs and events.',
  'Anders once convinced a queen to change her mind about an important royal decree.',
  'He’s famous for his smooth-talking ways that can turn any situation in his favor.',
  'Anders once persuaded a famous scholar to teach him ancient knowledge in exchange for a story.',
  'He once talked his way into getting the best table at a fully-booked restaurant.',
  'Anders has a talent for getting people to share their best stories with him.',
  'He once convinced a judge to dismiss a case with a single sentence.',
  'Anders can make people laugh so hard they forget what they were mad about.',
  'He once charmed a pirate captain into giving him a share of the treasure.',
  'Anders has a way of making people feel like they’ve known him for years after just one conversation.',
  'He once convinced a rival knight to let him win a jousting match for fun.',
  'Anders once talked a stubborn mule into carrying him across a desert.',
  'He’s known for his persuasive storytelling, which can make anyone believe in the impossible.',
  'Anders once convinced a group of travelers to join him on a spontaneous adventure.',
  'He once talked his way into getting free tickets to a sold-out show.',
  'Anders has a way of making people feel important, no matter who they are.',
  'He once persuaded an entire tavern to let him sing and perform for the night.',
  'Anders is known for his silver tongue, and many believe it’s his greatest weapon.'
],
    'daniel': [
  'Daniel the Great built an entire castle with his own hands.',
  'He once fought a dragon and emerged victorious.',
  'Daniel can solve any riddle in less than a minute.',
  'He once swam across the largest lake in the kingdom in a single day.',
  'Daniel once lifted a boulder twice his size to save a village.',
  'He’s known for his unmatched ability to lead armies into victorious battles.',
  'Daniel has a secret vault filled with ancient treasures he’s collected from his quests.',
  'He’s a master strategist, always ten steps ahead of his enemies.',
  'Daniel once crossed an entire desert without water, relying on his survival skills.',
  'He’s trained with the best sword fighters in the world, mastering every style of combat.',
  'Daniel’s favorite weapon is a sword he forged himself from enchanted steel.',
  'He can speak to animals, often relying on them to assist him on his adventures.',
  'Daniel once climbed the tallest mountain in the realm to retrieve a rare flower.',
  'He has a pet falcon named Blaze that scouts ahead for him on dangerous missions.',
  'Daniel is a master of ancient languages, able to read ancient runes and scrolls.',
  'He’s skilled in archery, known for hitting targets from incredible distances.',
  'Daniel once outwitted a sorcerer who was trying to steal his kingdom’s riches.',
  'He’s famous for his fairness and kindness, often helping those in need during his travels.',
  'Daniel once tamed a wild bear, turning it into a loyal companion.',
  'He discovered a hidden treasure buried deep within the catacombs of a forgotten city.',
  'Daniel’s sword is enchanted, glowing blue when danger is near.',
  'He once defended his kingdom from a massive invasion, outsmarting the enemy army.',
  'Daniel has never lost a duel, whether with swords, riddles, or words.',
  'He’s known for his incredible strength, able to move objects others couldn’t budge.',
  'Daniel once sailed across the seas to discover new lands, mapping uncharted territories.',
  'He was knighted at a young age after saving the royal family from an ambush.',
  'Daniel once survived for a month in the wilderness with nothing but his wits.',
  'He’s known for crafting intricate battle plans that seem impossible but always succeed.',
  'Daniel has the ability to blend into any environment, making him a master of stealth.',
  'He once escaped from a seemingly inescapable prison by outsmarting the guards.',
  'Daniel’s courage is known far and wide; he never backs down from a challenge.',
  'He once brokered peace between two warring nations with his diplomatic skills.',
  'Daniel has a hidden talent for music, playing the lute like a master.',
  'He’s known for his wisdom and often advises kings and queens on matters of state.',
  'Daniel once ventured into the deepest part of the forest to save a group of lost travelers.',
  'He’s famous for his unshakable loyalty to his friends and allies.',
  'Daniel has defeated monsters that others believed were invincible.',
  'He once outwitted a group of bandits by leading them into a trap of their own making.',
  'Daniel’s bravery has earned him the loyalty of many warriors and leaders alike.',
  'He once rescued a prince from a high tower guarded by a fearsome beast.',
  'Daniel’s knowledge of herbs and healing has saved many lives on the battlefield.',
  'He’s known to study ancient texts, learning the secrets of past civilizations.',
  'Daniel once fought off an entire horde of invaders with just his sword and shield.',
  'He has a network of informants throughout the kingdom, always keeping him one step ahead.',
  'Daniel’s leadership during battles is legendary; his troops would follow him anywhere.',
  'He once won a chess game against a master strategist known to be unbeatable.',
  'Daniel has discovered long-lost relics that were thought to be myths.',
  'He’s known to train from dawn till dusk, constantly improving his skills.',
  'Daniel once traveled through a dense jungle to recover an ancient artifact of great power.',
  'He’s been offered countless kingdoms to rule but prefers the life of a wandering adventurer.',
  'Daniel once thwarted an assassination attempt on the king by uncovering the plot beforehand.',
  'He’s famous for his ability to unite people of all backgrounds under a common cause.',
  'Daniel’s swordsmanship is unrivaled; many consider him the best warrior in the realm.',
  'He once saved a town from a marauding giant by tricking it into leaving peacefully.',
  'Daniel has a vast knowledge of ancient myths and legends, using them to guide his quests.',
  'He once freed an entire village that was under a dark curse.',
  'Daniel has a hidden refuge deep in the mountains where he retreats to think and train.',
  'He once fought off a pack of wolves with nothing but a wooden staff.',
  'Daniel’s kindness is as well-known as his strength, earning him the love of the people.',
  'He’s an expert tracker, able to find anyone or anything, no matter where they are hiding.',
  'Daniel once used his cunning to defeat an evil sorcerer who had trapped him in an illusion.',
  'He’s known for wearing a cloak that was gifted to him by a mysterious mage.',
  'Daniel once protected a caravan of merchants from a group of ruthless bandits.',
  'He’s traveled to the ends of the earth in search of lost knowledge and ancient wisdom.',
  'Daniel’s tactical mind has won many battles before they even began.',
  'He once calmed an angry dragon by speaking to it in its ancient tongue.',
  'Daniel has discovered hidden chambers in ancient ruins, uncovering their secrets.',
  'He once led an expedition through the desert to find a legendary oasis.',
  'Daniel’s knowledge of the stars allows him to navigate even the most treacherous terrains.',
  'He’s known to have a vast library filled with books from every corner of the world.',
  'Daniel once negotiated peace between rival factions, bringing harmony to the land.',
  'He’s skilled at forging his own weapons, making him a master craftsman as well as a warrior.',
  'Daniel has a secret passage in his castle that leads to a hidden vault of treasures.',
  'He once discovered a hidden island that was invisible to all but the most perceptive eyes.',
  'Daniel has a trusted circle of companions who aid him on his many adventures.',
  'He’s a master at disguises, able to blend into any crowd undetected.',
  'Daniel once solved an ancient puzzle that had baffled scholars for centuries.',
  'He once saved a village from a flood by redirecting the river with his engineering skills.',
  'Daniel has been known to meditate for hours to sharpen his mind before a big decision.',
  'He once rescued an entire town from a plague by finding a rare medicinal herb.',
  'Daniel’s sword has been passed down through generations, each warrior adding their own magic to it.',
  'He’s known for his ability to tame wild horses, making them his loyal steeds.',
  'Daniel once outmaneuvered a group of bounty hunters who were trying to capture him.',
  'He’s known to be able to read the weather, predicting storms long before they arrive.',
  'Daniel once defended a fortress from a siege that lasted for months, never losing hope.',
  'He’s a master of stealth, often sneaking into enemy camps undetected to gather intel.',
  'Daniel once found a lost city buried under the sands of the desert.',
  'He has trained in the art of combat with some of the greatest warriors in history.',
  'Daniel’s shield is enchanted to block even the strongest of magical attacks.',
  'He’s known for his incredible endurance, able to march for days without rest.',
  'Daniel once helped a village rebuild after it was destroyed by a storm, earning their eternal gratitude.',
  'He’s skilled in the art of persuasion, often convincing enemies to stand down without bloodshed.',
  'Daniel once battled a legendary sea monster while sailing across treacherous waters.',
  'He’s known for his keen sense of justice, never allowing the innocent to suffer.',
  'Daniel once discovered a long-lost artifact that was said to hold the power of the gods.',
  'He’s traveled to distant lands, learning from different cultures and bringing back their wisdom.',
  'Daniel has a magical compass that always points him toward his next great adventure.',
  'He once saved an entire kingdom by unraveling a dark conspiracy within the royal court.',
  'Daniel’s reputation as a hero has spread far and wide, with many seeking him out for help.',
  'He’s known for his humility, never boasting of his achievements despite his many victories.'
],

    'hanna': [
  'Hanna once fought off an entire army with nothing but a pillow.',
  'Her pillow has its own name: Fluffinator.',
  'Hanna can nap anywhere, even in the middle of a battlefield.',
  'She holds the world record for the longest pillow fight, which lasted 48 hours.',
  'Hanna’s pillow is enchanted, making it both soft and indestructible.',
  'She once turned a pillow into a parachute during an epic escape.',
  'Hanna can disarm an opponent with a single pillow swipe.',
  'Legend says her pillow gets fluffier the more she fights.',
  'She trains by practicing with 100 pillows at once.',
  'Hanna’s battle cry is a loud "Fluff it up!"',
  'She has never lost a pillow fight, even against giants.',
  'Hanna uses different pillows for different battles, each one uniquely designed.',
  'Her favorite pillow filling is made from clouds.',
  'Hanna once blocked an avalanche with her pillow.',
  'She’s been known to use pillows as shields in battle.',
  'Hanna’s pillow has a hidden pocket where she keeps secret treasures.',
  'She can leap into the air and cushion her fall with her trusty pillow.',
  'Hanna once defeated an entire team of warriors using only two pillows.',
  'Her pillowcase is made from the finest silk in the land.',
  'Hanna is a master of the "Double Fluff Strike," a rare pillow fighting technique.',
  'Her pillow glows in the dark, making night battles easier.',
  'She once built an entire pillow fortress to defend her village.',
  'Hanna has won every pillow tournament in the kingdom.',
  'Her pillow doubles as a blanket for impromptu naps.',
  'She can throw a pillow with perfect accuracy from 100 feet away.',
  'Hanna’s training includes daily naps to recharge her strength.',
  'She’s trained in pillow-to-pillow combat since she was a child.',
  'Her pillow was once stolen by a rival warrior, but Hanna won it back in a dramatic duel.',
  'Hanna has a secret pillow recipe that makes her pillows stronger than steel.',
  'Her pillow strikes are so fast, opponents often don’t see them coming.',
  'She once used her pillow to soften the landing for a falling dragon.',
  'Hanna’s pillow has been passed down through generations of pillow warriors.',
  'She can deflect arrows with a single swipe of her pillow.',
  'Hanna once rescued a town from a storm by creating a pillow barrier.',
  'She’s skilled at crafting her own pillows, which are known to be the softest in the land.',
  'Her pillow contains magical feathers that allow her to jump higher.',
  'Hanna’s favorite training exercise is balancing on one leg while pillow fighting.',
  'She’s known for her "Pillow Spin Attack," a move that leaves opponents dizzy.',
  'Hanna once stopped a charging bull with her pillow.',
  'She has a pillow for every occasion, including a travel-sized pillow for stealth missions.',
  'Hanna’s pillow is immune to fire, water, and all elements.',
  'She once won a pillow fight against a hundred warriors, all at the same time.',
  'Hanna’s pillowcase is embroidered with ancient runes of protection.',
  'She can knock out an opponent with a single pillow hit, but she prefers to go easy.',
  'Hanna’s battle pillow is filled with the softest feathers from mystical creatures.',
  'Her pillow can expand to twice its size during a fight, giving her the upper hand.',
  'Hanna can block a sword with her pillow as if it were a shield.',
  'She’s known to fall asleep in the middle of battles, only to wake up and win.',
  'Hanna’s pillow once saved her from falling off a cliff by acting as a trampoline.',
  'She carries a backup pillow at all times, just in case.',
  'Her pillow strikes are so powerful, they can send an opponent flying.',
  'Hanna’s favorite color is the soft pastel of her battle pillow.',
  'She trains by pillow fighting blindfolded to sharpen her instincts.',
  'Hanna’s pillow once stopped a tidal wave from reaching the shore.',
  'She has a special pillow for each day of the week, all with different powers.',
  'Hanna’s pillow once blocked a lightning bolt during a storm.',
  'She often carries extra pillows to throw at enemies from afar.',
  'Hanna’s pillow absorbs energy from the sun to gain more power during the day.',
  'Her pillow can split into two for dual-wielding pillow combat.',
  'She can pillow fight with one hand tied behind her back and still win.',
  'Hanna once used her pillow to cushion an entire village from an earthquake.',
  'Her pillow fluff is made from the softest wool, enchanted by a wizard.',
  'Hanna can balance a stack of pillows on her head while performing acrobatics.',
  'She once used her pillow to smother a fire and save a family from danger.',
  'Hanna’s pillow has its own personality and can sense when danger is near.',
  'She has a special pillow punch that creates shockwaves through the air.',
  'Hanna’s pillow can absorb sound, making her battles completely silent.',
  'She once built a bridge out of pillows to help people cross a river.',
  'Hanna is known for her "Pillow Whirlwind Attack," which creates a storm of fluff.',
  'Her pillow is enchanted to always return to her hand when thrown.',
  'Hanna’s pillow can grow larger to shield her entire body.',
  'She has a pillow that doubles as a sled for quick escapes down snowy mountains.',
  'Her pillow is filled with enchanted feathers that float, allowing her to glide through the air.',
  'Hanna once stopped a rolling boulder with a well-placed pillow.',
  'She’s known to decorate her pillow with fresh flowers before each battle.',
  'Hanna’s pillow can create a barrier that protects her from all attacks.',
  'Her pillow can be used as a raft in case of emergencies on the water.',
  'Hanna once used her pillow to fly over a canyon.',
  'She always carries a pillow just in case she needs a quick nap.',
  'Hanna’s pillow can inflate like a balloon to lift her above her enemies.',
  'Her pillow absorbs the impact of any blow, leaving her unharmed.',
  'Hanna has a special battle stance that involves balancing on her pillow.',
  'She can pillow fight while running at full speed.',
  'Hanna’s pillow is known to glow under the light of the full moon.',
  'She once used her pillow as a battering ram to break through a fortress wall.',
  'Hanna’s pillow can act as a parachute when she jumps from high places.',
  'Her pillow is enchanted to never get dirty, no matter how many battles she fights.',
  'She once trained in the mountains for a year, fighting only with her pillow.',
  'Hanna’s pillow has a calming effect on anyone who touches it.',
  'She can toss her pillow with pinpoint accuracy over long distances.',
  'Her pillow once saved her from an avalanche by acting as a barrier.',
  'Hanna’s pillow is waterproof, making it the perfect tool for underwater battles.',
  'She once used her pillow to cushion a wagon carrying precious cargo during a rough journey.',
  'Hanna has a special victory dance she performs after winning a pillow fight.',
  'Her pillow has a charm that keeps her safe from harm during her travels.',
  'She can spin her pillow in the air to create a protective vortex around her.',
  'Hanna’s pillow is soft enough to sleep on but tough enough to fight with.',
  'She once defended a village from an invading army with just her pillow.',
  'Hanna’s pillow has a mind of its own and sometimes helps her win battles.',
  'Her pillow can change color depending on her mood.',
  'Hanna once used her pillow to create a safe landing for a falling meteor.',
  'She has a legendary pillow fighting technique known as the "Fluff Storm."',
  'Hanna’s pillow once stopped a speeding arrow mid-air.',
  'Her pillow is imbued with ancient magic, making it her most trusted companion in battle.'
]

  };

  return facts[person];
}
